name: Compile Kernel

# COMET Worfklow [240904]
# by mrcxlinux

# this workflow is meant to build "Apollo Kernel" for 9810
# to change build options go to "BUILD_KERNEL" in apollo.sh

# Build: Galaxy S9+ KOR (G965N)
# CR_TARGET=5
# CR_COMPILER=4 (clang 20)
# CR_SELINUX=2 (enforcing)
# CR_KSU="y" (enabled)
# CR_CLEAN="n" (dirty build)

on:
  workflow_dispatch:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Init submodules
      run: |
        git submodule update --init --recursive
        cd KernelSU-Next
        # git checkout 53791c92bff13d62338f29cc9da035a37652ca91
        git checkout legacy-susfs-v2
        cd ..
        git add KernelSU-Next

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y zip bsdiff tar xz-utils build-essential

    - name: Download Clang 20 toolchain
      run: |
        mkdir -p ../compiler/clang-20.0.0-r547379
        wget -qO- "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz" \
          | tar --use-compress-program=unzstd -xv -C ../compiler/clang-20.0.0-r547379

    - name: Run apollo.sh
      id: run_apollo
      run: |
        mkdir -p Apollo/Out
        ./apollo.sh -cli 5 4 2 y n 2>&1 | tee apollo_output.log

    - name: Check script status
      run: |
        if grep -q "Aborting" apollo_output.log; then
          echo "Aborting found in output, failing the job"
          exit 1
        else
          echo "No 'Aborting' found, job succeeded"
        fi

    # Upload the output log as an artifact
    - name: Upload apollo output log
      uses: actions/upload-artifact@v4
      with:
        name: apollo-log
        path: apollo_output.log

    # Upload all files in the Apollo/Product directory as an artifact
    - name: Upload final files
      uses: actions/upload-artifact@v4
      with:
        name: kernel-apollo-final
        path: Apollo/Product/**

